
parameters:
  _param:
    salt_minion_ca_host: ${_param:infra_config_hostname}.${_param:cluster_domain}
    salt_minion_ca_authority: salt_master_ca

    # kubernetes settings
    kubernetes_admin_user: admin
    kubernetes_admin_password: Lats3iPyP8cllqam
    kubernetes_admin_token: 2XMTcep6HKlsLGii9JZ2CmsfW9RAN4tt
    kubernetes_kubelet_token: ftcILfFWiH8HVWOYTxUbM64X8hqDPbn5
    kubernetes_kube-proxy_token: SiyU5ghQDMTcGRVEl65qOVyuTiS7zLov
    kubernetes_scheduler_token: ajCM6ZSRNQDYMxnn1TFbDp9jwjDkf6pJ
    kubernetes_controller-manager_token: KqIVQNP2t1BwrKpFf84c3tH2eE0x5yTJ
    kubernetes_dns_token: yEpLOnTvhLkYS4JYv9kDHQVsRORf1OP1
    etcd_initial_token: HyC1DppCBt0r6rpqpZYA1Uy6C1u8FpCa

    # addresses and hostnames
    kubernetes_internal_api_address: 10.254.0.1
    kubernetes_control_hostname: ctl
    kubernetes_control_address: 10.0.1.10
    kubernetes_control_node01_hostname: ctl01
    kubernetes_control_node02_hostname: ctl02
    kubernetes_control_node03_hostname: ctl03
    kubernetes_control_node01_address: 10.0.1.11
    kubernetes_control_node02_address: 10.0.1.12
    kubernetes_control_node03_address: 10.0.1.13

    cluster_vip_address: ${_param:kubernetes_control_address}
    cluster_local_address: ${_param:single_address}

    # etcd stuff
    cluster_node01_hostname: ${_param:kubernetes_control_node01_hostname}
    cluster_node01_address: ${_param:kubernetes_control_node01_address}
    cluster_node01_port: 4001
    cluster_node02_hostname: ${_param:kubernetes_control_node02_hostname}
    cluster_node02_address: ${_param:kubernetes_control_node02_address}
    cluster_node02_port: 4001
    cluster_node03_hostname: ${_param:kubernetes_control_node03_hostname}
    cluster_node03_address: ${_param:kubernetes_control_node03_address}
    cluster_node03_port: 4001

    kubernetes_virtlet_enabled: False
    # calico
    calico_private_network: 192.168.0.0
    calico_private_netmask: 16
    kubernetes_control_node01_tenant_address: 172.16.11.11
    kubernetes_control_node02_tenant_address: 172.16.11.12
    kubernetes_control_node03_tenant_address: 172.16.11.13

  linux:
    network:
      host:
        ctl:
          address: ${_param:kubernetes_control_address}
          names:
          - ${_param:kubernetes_control_hostname}
          - ${_param:kubernetes_control_hostname}.${_param:cluster_domain}
        ctl01:
          address: ${_param:kubernetes_control_node01_address}
          names:
          - ${_param:kubernetes_control_node01_hostname}
          - ${_param:kubernetes_control_node01_hostname}.${_param:cluster_domain}
        ctl02:
          address: ${_param:kubernetes_control_node02_address}
          names:
          - ${_param:kubernetes_control_node02_hostname}
          - ${_param:kubernetes_control_node02_hostname}.${_param:cluster_domain}
        ctl03:
          address: ${_param:kubernetes_control_node03_address}
          names:
          - ${_param:kubernetes_control_node03_hostname}
          - ${_param:kubernetes_control_node03_hostname}.${_param:cluster_domain}
